### ISSUE TITLE
Underscore-delimited / hyphen-delimited

### ISSUE THREAD

**Issue by trevorbaca** [GregoryREvans/hamon_shu#1]
Hey Greg, Awesome to see a new repo. Very small observation about the casing of repo names. GitHub allows repo names in a variety of case types: hyphen-delimited `hamon-shu` and underscore-delimited `hamon_shu` both work.

For a couple of years I went with hyphen-delimited repo names (just like you're doing here), and that certainly does work.

But over the years I discovered one minor annoyance: if the repo is ever going to turn into a Python package (for other ppl to install), then Python will insist on underscore-delimited `hamon_shu` for the package name (because Python forbids hyphen-delimited identifiers). It is, of course, absolutely fine to have a repo named `hamon-shu` that contains within it a Python package named `hamon_shu`. But if casing is all the same to you, then you might be happier naming the repo exactly the same as the package itself (ie, eschewing hyphen-delimited names).

**Comment by GregoryREvans** [comment]
Thanks for the tip. I'll keep it in mind for future projects.
